<?php

use Illuminate\Database\Seeder;

class BarrioTablaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('TB_SRD_BARRIO')->delete();
        DB::table('TB_SRD_BARRIO')->insert([
            ['V_NOMBRE_BARRIO' => 'Canaima', 'V_COD_UPZ' => 1],
            ['V_NOMBRE_BARRIO' => 'Tibabita Rural', 'V_COD_UPZ' => 1],
            ['V_NOMBRE_BARRIO' => 'Torca I', 'V_COD_UPZ' => 1],
            ['V_NOMBRE_BARRIO' => 'Torca II', 'V_COD_UPZ' => 1],
            ['V_NOMBRE_BARRIO' => 'El Redil', 'V_COD_UPZ' => 10],
            ['V_NOMBRE_BARRIO' => 'La Granja Norte', 'V_COD_UPZ' => 10],
            ['V_NOMBRE_BARRIO' => 'La Uribe', 'V_COD_UPZ' => 10],
            ['V_NOMBRE_BARRIO' => 'San Antonio Noroccidental', 'V_COD_UPZ' => 10],
            ['V_NOMBRE_BARRIO' => 'San Jose De Usaquen', 'V_COD_UPZ' => 10],
            ['V_NOMBRE_BARRIO' => 'Santa Teresa', 'V_COD_UPZ' => 10],
            ['V_NOMBRE_BARRIO' => 'Barrancas', 'V_COD_UPZ' => 11],
            ['V_NOMBRE_BARRIO' => 'Barrancas Norte', 'V_COD_UPZ' => 11],
            ['V_NOMBRE_BARRIO' => 'Barrancas Oriental rural', 'V_COD_UPZ' => 11],
            ['V_NOMBRE_BARRIO' => 'Bosque De Pinos', 'V_COD_UPZ' => 11],
            ['V_NOMBRE_BARRIO' => 'La Cita', 'V_COD_UPZ' => 11],
            ['V_NOMBRE_BARRIO' => 'San Cristobal Norte', 'V_COD_UPZ' => 11],
            ['V_NOMBRE_BARRIO' => 'Santa Cecilia Puente Norte', 'V_COD_UPZ' => 11],
            ['V_NOMBRE_BARRIO' => 'El Toberin', 'V_COD_UPZ' => 12],        
            ['V_NOMBRE_BARRIO' => 'Estrella Del Norte', 'V_COD_UPZ' => 12],
            ['V_NOMBRE_BARRIO' => 'La Liberia', 'V_COD_UPZ' => 12],
            ['V_NOMBRE_BARRIO' => 'La Pradera Norte', 'V_COD_UPZ' => 12],
            ['V_NOMBRE_BARRIO' => 'Las Orquideas', 'V_COD_UPZ' => 12],
            ['V_NOMBRE_BARRIO' => 'Acacias Usaquen', 'V_COD_UPZ' => 13],
            ['V_NOMBRE_BARRIO' => 'Bosque De Pinos I', 'V_COD_UPZ' => 13],
            ['V_NOMBRE_BARRIO' => 'Bosque De Pinos III', 'V_COD_UPZ' => 13],
            ['V_NOMBRE_BARRIO' => 'Caobos Salazar', 'V_COD_UPZ' => 13],
            ['V_NOMBRE_BARRIO' => 'Cedritos', 'V_COD_UPZ' => 13],
            ['V_NOMBRE_BARRIO' => 'Cedro Narvaez', 'V_COD_UPZ' => 13],
            ['V_NOMBRE_BARRIO' => 'Cedro Salazar', 'V_COD_UPZ' => 13],
            ['V_NOMBRE_BARRIO' => 'El Contador', 'V_COD_UPZ' => 13],
            ['V_NOMBRE_BARRIO' => 'Las Margaritas', 'V_COD_UPZ' => 13],
            ['V_NOMBRE_BARRIO' => 'Lisboa', 'V_COD_UPZ' => 13],
            ['V_NOMBRE_BARRIO' => 'Los Cedros', 'V_COD_UPZ' => 13],
            ['V_NOMBRE_BARRIO' => 'Los Cedros Oriental', 'V_COD_UPZ' => 13],
            ['V_NOMBRE_BARRIO' => 'Segundo Contador', 'V_COD_UPZ' => 13],
            ['V_NOMBRE_BARRIO' => 'Bella Suiza', 'V_COD_UPZ' => 14],
            ['V_NOMBRE_BARRIO' => 'Escuela De Caballeria I', 'V_COD_UPZ' => 14],
            ['V_NOMBRE_BARRIO' => 'Escuela De Caballeria II', 'V_COD_UPZ' => 14],
            ['V_NOMBRE_BARRIO' => 'Escuela De Infanteria', 'V_COD_UPZ' => 14],
            ['V_NOMBRE_BARRIO' => 'Ginebra', 'V_COD_UPZ' => 14],
            ['V_NOMBRE_BARRIO' => 'Ginebra II', 'V_COD_UPZ' => 14],
            ['V_NOMBRE_BARRIO' => 'Paramo Urbano I', 'V_COD_UPZ' => 14],
            ['V_NOMBRE_BARRIO' => 'San Gabriel Norte', 'V_COD_UPZ' => 14],
            ['V_NOMBRE_BARRIO' => 'San Gabriel Norte II', 'V_COD_UPZ' => 14],
            ['V_NOMBRE_BARRIO' => 'Santa Ana', 'V_COD_UPZ' => 14],
            ['V_NOMBRE_BARRIO' => 'Santa Ana Occidental', 'V_COD_UPZ' => 14],
            ['V_NOMBRE_BARRIO' => 'Santa Barbara Oriental', 'V_COD_UPZ' => 14],
            ['V_NOMBRE_BARRIO' => 'Usaquen', 'V_COD_UPZ' => 14],
            ['V_NOMBRE_BARRIO' => 'Country Club', 'V_COD_UPZ' => 15],
            ['V_NOMBRE_BARRIO' => 'La Calleja', 'V_COD_UPZ' => 15],
            ['V_NOMBRE_BARRIO' => 'La Carolina', 'V_COD_UPZ' => 15],
            ['V_NOMBRE_BARRIO' => 'Molinos Norte', 'V_COD_UPZ' => 16],
            ['V_NOMBRE_BARRIO' => 'Rincon Del Chico', 'V_COD_UPZ' => 16],
            ['V_NOMBRE_BARRIO' => 'San Patricio', 'V_COD_UPZ' => 16],
            ['V_NOMBRE_BARRIO' => 'Santa Barbara Central', 'V_COD_UPZ' => 16],
            ['V_NOMBRE_BARRIO' => 'Santa Barbara Occidental', 'V_COD_UPZ' => 16],
            ['V_NOMBRE_BARRIO' => 'Santa Bibiana', 'V_COD_UPZ' => 16],
            ['V_NOMBRE_BARRIO' => 'Buenavista', 'V_COD_UPZ' => 9],
            ['V_NOMBRE_BARRIO' => 'El Cerezo', 'V_COD_UPZ' => 9],
            ['V_NOMBRE_BARRIO' => 'El Rocio Norte', 'V_COD_UPZ' => 9],
            ['V_NOMBRE_BARRIO' => 'El Vervenal', 'V_COD_UPZ' => 9],
            ['V_NOMBRE_BARRIO' => 'Horizontes Norte', 'V_COD_UPZ' => 9],
            ['V_NOMBRE_BARRIO' => 'La Estrellita I', 'V_COD_UPZ' => 9],
            ['V_NOMBRE_BARRIO' => 'La Estrellita II', 'V_COD_UPZ' => 9],
            ['V_NOMBRE_BARRIO' => 'La Estrellita III', 'V_COD_UPZ' => 9],
            ['V_NOMBRE_BARRIO' => 'Mirador Del Norte II', 'V_COD_UPZ' => 9],
            ['V_NOMBRE_BARRIO' => 'San Antonio Norte', 'V_COD_UPZ' => 9],
            ['V_NOMBRE_BARRIO' => 'Tibabita', 'V_COD_UPZ' => 9],
            ['V_NOMBRE_BARRIO' => 'Tibabita I', 'V_COD_UPZ' => 9],
            ['V_NOMBRE_BARRIO' => 'Verbenal San Antonio', 'V_COD_UPZ' => 9],
            ['V_NOMBRE_BARRIO' => 'La Arboleda Rural', 'V_COD_UPZ' => 204],
            ['V_NOMBRE_BARRIO' => 'Siberia', 'V_COD_UPZ' => 202],
            ['V_NOMBRE_BARRIO' => 'Siberia II', 'V_COD_UPZ' => 202],
            ['V_NOMBRE_BARRIO' => 'Paramo III Rural', 'V_COD_UPZ' => 201],
            ['V_NOMBRE_BARRIO' => 'Bellavista', 'V_COD_UPZ' => 88],
            ['V_NOMBRE_BARRIO' => 'El Bagazal', 'V_COD_UPZ' => 88],
            ['V_NOMBRE_BARRIO' => 'El Nogal', 'V_COD_UPZ' => 88],
            ['V_NOMBRE_BARRIO' => 'El Refugio', 'V_COD_UPZ' => 88],
            ['V_NOMBRE_BARRIO' => 'El Retiro', 'V_COD_UPZ' => 88],
            ['V_NOMBRE_BARRIO' => 'Emaus', 'V_COD_UPZ' => 88],
            ['V_NOMBRE_BARRIO' => 'La Cabrera', 'V_COD_UPZ' => 88],
            ['V_NOMBRE_BARRIO' => 'Los Rosales', 'V_COD_UPZ' => 88],
            ['V_NOMBRE_BARRIO' => 'Paramo I Rural', 'V_COD_UPZ' => 88],
            ['V_NOMBRE_BARRIO' => 'Seminario', 'V_COD_UPZ' => 88],
            ['V_NOMBRE_BARRIO' => 'Paramo Urbano III', 'V_COD_UPZ' => 89],
            ['V_NOMBRE_BARRIO' => 'San Isidro', 'V_COD_UPZ' => 89],
            ['V_NOMBRE_BARRIO' => 'San Luis Altos Del Cabo', 'V_COD_UPZ' => 89],
            ['V_NOMBRE_BARRIO' => 'Bosque Calderon', 'V_COD_UPZ' => 90],
            ['V_NOMBRE_BARRIO' => 'El Paraiso', 'V_COD_UPZ' => 90],
            ['V_NOMBRE_BARRIO' => 'Granada', 'V_COD_UPZ' => 90],
            ['V_NOMBRE_BARRIO' => 'Ingemar', 'V_COD_UPZ' => 90],
            ['V_NOMBRE_BARRIO' => 'Ingemar Oriental', 'V_COD_UPZ' => 90],
            ['V_NOMBRE_BARRIO' => 'Juan XXIII', 'V_COD_UPZ' => 90],
            ['V_NOMBRE_BARRIO' => 'La Salle', 'V_COD_UPZ' => 90],
            ['V_NOMBRE_BARRIO' => 'Las Acacias', 'V_COD_UPZ' => 90],
            ['V_NOMBRE_BARRIO' => 'Maria Cristina', 'V_COD_UPZ' => 90],
            ['V_NOMBRE_BARRIO' => 'Pardo Rubio', 'V_COD_UPZ' => 90],
            ['V_NOMBRE_BARRIO' => 'San Isidro Rural', 'V_COD_UPZ' => 202],
            ['V_NOMBRE_BARRIO' => 'Siberia', 'V_COD_UPZ' => 90],
            ['V_NOMBRE_BARRIO' => 'Siberia Central', 'V_COD_UPZ' => 90],
        ]);
    }
}
