<?php

use Illuminate\Database\Seeder;

class EtapaTablaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('TB_SRD_ETAPA')->delete();
        DB::table('TB_SRD_ETAPA')->insert([
            
            /************CONVENCIONAL************/
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'RESERVA DEPORTIVA I', 'V_POR_ESTIMULO'=>'0'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'RESERVA DEPORTIVA II', 'V_POR_ESTIMULO'=>'0'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'ELITE NACIONAL I', 'V_POR_ESTIMULO'=>'0.5'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'ELITE NACIONAL II', 'V_POR_ESTIMULO'=>'1.0'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'ELITE NACIONAL III', 'V_POR_ESTIMULO'=>'1.25'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'ELITE NACIONAL IV', 'V_POR_ESTIMULO'=>'1.5'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'ELITE NACIONAL V', 'V_POR_ESTIMULO'=>'1.75'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'ELITE NACIONAL VI', 'V_POR_ESTIMULO'=>'2.0'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'ELITE NACIONAL VII', 'V_POR_ESTIMULO'=>'2.5'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'ELITE NACIONAL VIII', 'V_POR_ESTIMULO'=>'3.0'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'ELITE INTERNACIONAL I', 'V_POR_ESTIMULO'=>'0.5'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'ELITE INTERNACIONAL II', 'V_POR_ESTIMULO'=>'1.0'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'ELITE INTERNACIONAL III', 'V_POR_ESTIMULO'=>'1.25'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'ELITE INTERNACIONAL IV', 'V_POR_ESTIMULO'=>'1.5'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'ELITE INTERNACIONAL V', 'V_POR_ESTIMULO'=>'1.75'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'ELITE INTERNACIONAL VI', 'V_POR_ESTIMULO'=>'2.0'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'ELITE INTERNACIONAL VII', 'V_POR_ESTIMULO'=>'3.0'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 1, 'V_NOMBRE_ETAPA' => 'RETIRADO', '0'=>'3.0'],
            
            /*****PARALIMPICO*******/            
            ['FK_I_ID_TIPO_DEPORTISTA' => 2, 'V_NOMBRE_ETAPA' => 'ELITE PARANACIONAL I', 'V_POR_ESTIMULO'=>'1.0'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 2, 'V_NOMBRE_ETAPA' => 'ELITE PARANACIONAL II', 'V_POR_ESTIMULO'=>'1.0'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 2, 'V_NOMBRE_ETAPA' => 'ELITE PARANACIONAL III', 'V_POR_ESTIMULO'=>'1.5'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 2, 'V_NOMBRE_ETAPA' => 'ELITE PARANACIONAL IV', 'V_POR_ESTIMULO'=>'2.0'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 2, 'V_NOMBRE_ETAPA' => 'ELITE PARANACIONAL V', 'V_POR_ESTIMULO'=>'2.5'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 2, 'V_NOMBRE_ETAPA' => 'ELITE PARANACIONAL VI', 'V_POR_ESTIMULO'=>'3.0'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 2, 'V_NOMBRE_ETAPA' => 'ELITE INTERNACIONAL I', 'V_POR_ESTIMULO'=>'0.5'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 2, 'V_NOMBRE_ETAPA' => 'ELITE INTERNACIONAL II', 'V_POR_ESTIMULO'=>'1.0'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 2, 'V_NOMBRE_ETAPA' => 'ELITE INTERNACIONAL III', 'V_POR_ESTIMULO'=>'1.5'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 2, 'V_NOMBRE_ETAPA' => 'ELITE INTERNACIONAL IV', 'V_POR_ESTIMULO'=>'2.0'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 2, 'V_NOMBRE_ETAPA' => 'ELITE INTERNACIONAL V', 'V_POR_ESTIMULO'=>'3.0'],
            ['FK_I_ID_TIPO_DEPORTISTA' => 2, 'V_NOMBRE_ETAPA' => 'RETIRADO', '0'=>'3.0'],
    
        ]);
    }
}
